In [1]:
import numpy as np

In [2]:
mylist=[1,2,3]
type(mylist)

list

In [3]:
mylist*2

[1, 2, 3, 1, 2, 3]

In [4]:
#create an array in numpy
myarr=np.array(mylist)
type(myarr)

numpy.ndarray

In [5]:
print(myarr)

[1 2 3]


In [6]:
myarr*2

array([2, 4, 6])

In [7]:
#check the dimension of array(use ndim)
myarr.ndim

1

In [8]:
newarr=np.array([[1,2,3],[4,5,6]])

In [9]:
newarr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
newarr.ndim

2

In [11]:
#shape of the data
newarr.shape

(2, 3)

In [12]:
myarr.shape

(3,)

In [13]:
newarr.dtype  #dataype

dtype('int32')

In [14]:
newarr.itemsize #no of byte size variable is using

4

In [15]:
newarr.size # no of elements

6

In [16]:
#rows and column
newarr.shape


(2, 3)

In [17]:
# Reshape the array newarr.reshape(3,2) reshape the array within the column

In [18]:
newarr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
newarr.astype('float') #type casting

array([[1., 2., 3.],
       [4., 5., 6.]])

In [20]:
#resize array
np.resize(newarr,(2,4))

array([[1, 2, 3, 4],
       [5, 6, 1, 2]])

In [21]:
newarr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
newarr[1,1]

5

In [23]:
newarr[1,1]=8

In [24]:
newarr

array([[1, 2, 3],
       [4, 8, 6]])

In [25]:
myarr

array([1, 2, 3])

In [26]:
myarr[0:2] # a(i:j+1)-i-start index,j-end index

array([1, 2])

In [27]:
myarr

array([1, 2, 3])

In [28]:
myarr[1:2]

array([2])

In [29]:
a=np.array([1,2,3,5,9,6])
a

array([1, 2, 3, 5, 9, 6])

In [30]:
a[1::2]#jump 2 values 

array([2, 5, 6])

In [31]:
a[1::3] #jump 3 values

array([2, 9])

In [32]:
a[::-1]#print array in reverse

array([6, 9, 5, 3, 2, 1])

In [33]:
a[::-2]

array([6, 5, 2])

In [34]:
a[-1]

6

In [35]:
a[-2]

9

In [36]:
a[-3]

5

In [37]:
b=np.array([[1,2],[3,4],[5,6],[7,8]])

In [38]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [39]:
b[1::0],[1::1]

SyntaxError: invalid syntax (<ipython-input-39-016725ad5f65>, line 1)

In [ ]:
import numpy as np

In [ ]:
b=np.array([[1,2],[3,4],[5,6],[7,8]])

In [41]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [42]:
b[1]


array([3, 4])

In [40]:
b[1:3]

array([[3, 4],
       [5, 6]])

In [45]:
b[0:,1]

array([2, 4, 6, 8])

In [46]:
b[0:3,1]

array([2, 4, 6])

In [47]:
b[1:3]

array([[3, 4],
       [5, 6]])

In [48]:
b[1]

array([3, 4])

In [49]:
b[2:]

array([[5, 6],
       [7, 8]])

In [50]:
b[1:,0]

array([3, 5, 7])

In [51]:
b[0:,0]

array([1, 3, 5, 7])

In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [91]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
a[0:,1]

array([2, 5])

In [93]:
a[1]

array([4, 5, 6])

In [94]:
a[1:]


array([[4, 5, 6]])

In [95]:
a[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [96]:
a[1:3,0:2]

array([[4, 5]])

In [97]:
a[0:,1]

array([2, 5])

In [98]:
a[1:,1:]

array([[5, 6]])

In [99]:
a[1:,2:]

array([[6]])

In [60]:
import numpy as np


In [61]:
a=np.array((1,2,3))

In [62]:
a

array([1, 2, 3])

In [63]:
import numpy as np

In [64]:
a=np.array([[1,2,3],[4,5,6]])

In [65]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
#transpose
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [68]:
#to access values in an interval
b=np.linspace(1,3,20)

In [69]:
b

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

In [ ]:
b=np.linspace(1,10,10)
b

In [70]:
#min value in an array
b

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

In [71]:
b.min()


1.0

In [72]:
#max value in an array
b.max()

3.0

In [73]:
#find the sum in an array
print(b)
b.sum()

[1.         1.10526316 1.21052632 1.31578947 1.42105263 1.52631579
 1.63157895 1.73684211 1.84210526 1.94736842 2.05263158 2.15789474
 2.26315789 2.36842105 2.47368421 2.57894737 2.68421053 2.78947368
 2.89473684 3.        ]


40.0

In [74]:
#sum of rows and columns in an array
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
print(b)
print("sum of all the values:",b.sum())
print("sum of along column:",b.sum(axis=0))
print("sum of along rows:",b.sum(axis=1))

[[1 2 3]
 [4 5 6]]
sum of all the values: 21
sum of along column: [5 7 9]
sum of along rows: [ 6 15]


In [76]:
#squaring of values
b**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [77]:
#squareroot of values
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [78]:
#adding two arrays
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[1,2,3],[4,5,6]])
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [79]:
#substracting two arrays
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0]])

In [80]:
#multipication of two arrays
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [81]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [82]:
#stack arrays in vertical
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
#stack array in horizontal
np.hstack((arr1,arr2))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [84]:
import numpy as np

In [85]:
#create a sequence of numbers
np.arange(10,40,4)

array([10, 14, 18, 22, 26, 30, 34, 38])

In [86]:
#to create array of 1
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [87]:
#to create array of 0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [88]:
#changing data type of  elements within an array
np.ones(10).astype(int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [89]:
#empty array
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [90]:
#rand is function inside the random class and its gives a random values of 2 rows and 3 columns
np.random.rand(2,3)#2*3

array([[0.88755574, 0.1574153 , 0.21568544],
       [0.70591506, 0.02780974, 0.83778325]])

## Numpy for Linear algebra

In [ ]:
import numpy as np

In [ ]:
a=26.6

In [ ]:
np.isscalar(a)

In [ ]:
np.isscalar([2])

In [ ]:
#scalar computation
s1=6
s2=4

In [ ]:
print(s1+s2)

In [ ]:
print(s1-s2)
print(s1*s2)
print(s1/s2)
print(s1//s2)

In [ ]:
#vector
a=[1,2,3]
a

In [ ]:
a*2 #incorrect

In [ ]:
np.array(a)*2 #correct

In [ ]:
np.array(a)+2#adding scalar to matrix

In [ ]:
np.add(a,2)#another way

In [ ]:
np.subtract(a,2)#subtract scalar to vector

In [ ]:
np.multiply(a,2)#multipy scalar to vector

In [ ]:
np.divide(a,2)#dividing saclar to vector

In [ ]:
#Matrix related computation
a=np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
#matrix addiotion
a+b

In [ ]:
#matrix subtraction
a-b

In [ ]:
#matrix multiplication
a*b

In [ ]:
a/b

In [ ]:
np.add(a,b)

In [ ]:
np.subtract(a,b)

In [ ]:
np.multiply(a,b)

In [ ]:
np.divide(a,b)

In [ ]:
A=np.array([[7,1],[2,3]])
A

In [ ]:
A*7

In [ ]:
A*1/7

In [ ]:
A+2

In [ ]:
np.add(A,2)

In [ ]:
np.multiply(A,2)

In [ ]:
A/7

In [ ]:
#dot product
a=[1,2,3]
b=[4,5,6]
np.dot(a,b)

In [ ]:
np.cross(a,b)

In [ ]:
#matrix  matrix multiplication
x=np.array([[1,2],[4,3]])
y=([[3,4],[3,10]])


In [ ]:
x,y

In [ ]:
x+y

In [ ]:
np.add(x,y)

In [ ]:
x-y

In [ ]:
#matrix multipication using vector
A=np.array([[3,4,2]])
B=np.array([[13,9,7,15],[8,7,4,6],[6,4,0,3]])
A,B

In [ ]:
np.matmul(A,B)

In [ ]:
#matrix multiplication is not commutative
G=np.array([[1,2],[4,5]])
H=np.array([[6,7],[8,8]])
np.matmul(G,H)

In [ ]:
np.matmul(H,G)

In [ ]:
np.transpose(G)

In [ ]:
G

In [ ]:
I=np.array([[1,0],[0,1]])

In [ ]:
np.matmul(G,I)

In [ ]:
G_inv=np.linalg.inv(G)
G_inv

In [ ]:
np.matmul(G,G_inv)

In [ ]:
#linear system of equation
#x+y+z=3
#2x+3y+7z=0
#x+3y-2z+17
A=np.array([[1,1,1],[2,3,7],[1,3,-2]])
B=np.array([3,0,17])
np.linalg.solve(A,B)

In [ ]:
#eigen value problem
E=np.array([[-6,3],[4,5]])
E

In [ ]:
w,v=np.linalg.eig(E)

In [ ]:
w

In [ ]:
v

In [ ]:
np.multiply(w,v)

In [ ]:
np.matmul(E,v)

## calculus

In [ ]:
#derivative

In [ ]:
from scipy.misc import derivative

In [ ]:
def f(x):
    return 2*x

In [ ]:
derivative(f,8)

In [ ]:
def f(x):
    return(3*x + 4*x)

In [ ]:
derivative(f,4)